name: advisor
description: A magic advisor app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.0.0
  get_it: ^7.6.0

dev_dependencies:
  test: ^1.21.4
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  flutter_lints: ^2.0.1
  mockito: ^5.3.2
  mocktail: ^0.3.0
  bloc_test: ^9.1.3
  platform: ^3.1.0
  file: ^6.1.4



flutter:

 
  uses-material-design: true
