name: todo_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  go_router: ^8.2.0
  flutter_adaptive_scaffold: ^0.1.5
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.5
  uuid: ^3.0.7
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  shimmer_animation: ^2.1.0+1
  json_annotation: ^4.8.1
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  mocktail: ^0.3.0
  build_runner: ^2.4.6 
  flutter_lints: ^2.0.1
  bloc_test: ^9.1.3
  json_serializable: ^6.7.1



flutter:


  uses-material-design: true

  
