// Mocks generated by Mockito 5.4.2 from annotations
// in todo_app/test/1_domain/use_cases/load_overview_todo_collection_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:either_dart/src/either.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_app/0_data/repositories/todo_repository_mock.dart' as _i3;
import 'package:todo_app/1_domain/entities/todo_collection.dart' as _i6;
import 'package:todo_app/1_domain/failures/failure.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ToDoRepositoryMock].
///
/// See the documentation for Mockito's code generation for more information.
class MockToDoRepositoryMock extends _i1.Mock
    implements _i3.ToDoRepositoryMock {
  @override
  _i4.Future<
      _i2.Either<_i5.Failure,
          List<_i6.ToDoCollection>>> readToDoCollections() =>
      (super.noSuchMethod(
        Invocation.method(
          #readToDoCollections,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.ToDoCollection>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.ToDoCollection>>(
          this,
          Invocation.method(
            #readToDoCollections,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.ToDoCollection>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.ToDoCollection>>(
          this,
          Invocation.method(
            #readToDoCollections,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ToDoCollection>>>);
}
